### ISSUE TITLE
Support all types of query parameters

### ISSUE THREAD

**Issue by schernolyas** [schernolyas/hibernate-ogm#1]
Class org.hibernate.datastore.ogm.orientdb.OrientDBDialect. Method executeBackendQuery.
Need supports other types

**Comment by cristhiank** [comment]
@schernolyas  Thanks for adding to your repo, but I think we can work with separated repos, that's why Pull Requests and Git exists, there is no need to work in the same repo, I already forked the OGM repo and I will start commiting to that repo.
Just one question, In this repo which test should I run to start working ? I see you have a lot of changes in many files.

**Comment by schernolyas** [comment]
Hi @cristhiank ! Thank You for your answer. But I am not understand that You try to do. I think that We develop my implementation together and send to Davide.

**Comment by cristhiank** [comment]
@schernolyas  I think it's better to work each one in his own repo and send the pull requests to Davide, it's the normal way to contribute to open source projects. I have done the same with many others.

**Comment by schernolyas** [comment]
@cristhiank Can You apply my invitation in google hangout?

**Comment by schernolyas** [comment]
Thank You!

**Comment by DavideD** [comment]
> @schernolyas Thanks for adding to your repo, but I think we can work with separated repos, that's why Pull Requests and Git exists, there is no need to work in the same repo, I already forked the OGM repo and I will start commiting to that repo.
> Just one question, In this repo which test should I run to start working ? I see you have a lot of changes in many files.

Yes, I don't think there is need  for a new repository, unless you both prefer to work that way.
Since you are both working on this, you will probably need to coordinate a bit around the issues to solve.

**Comment by schernolyas** [comment]
Mostly fixed. Need test for all types.
P.S. also, linked with dates ( see issue #2)

**Comment by schernolyas** [comment]
fixed. Test created
